---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 2
  type: ReplicaSet
  version: "4.2.6"
  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - command:
                - chown
                - -R
                - "2000"
                - /data
              name: busybox
              image: busybox
              volumeMounts:
                - mountPath: /data
                  name: data-volume
                - mountPath: /log
                  name: logs-volume
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            selector:
              matchLabels:
                type: data
            storageClassName: local-storage
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            selector:
              matchLabels:
                type: log
            storageClassName: local-storage
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: bkkAdmin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
