apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-log
spec:
  storageClassName: manual-log
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/davidkrisztian/Work/logs/mongo/mongo.log