apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  storageClassName: manual-data
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/davidkrisztian/Work/data/mongo